enable-module-update = true


# Morphe
[YouTube-Morphe]
app-name = "YouTube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
patches-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "module"
patcher-args = "-e 'Custom branding' -OappIcon=original"

[YT-Music-Morphe]
app-name = "YT Music"
direct-dlurl = "https://eb5e7388c3df147b74dd2379b7cf8323.r2.cloudflarestorage.com/downloadprod/wp-content/uploads/2026/05/94/6a1743405b509/com.google.android.apps.youtube.music_9.20.53-92053230_minAPI26%28armeabi-v7a%29%28nodpi%29_apkmirror.com.apk?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=72a5ba3a0b8a601e535d5525f12f8177%2F20261006%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20261006T072842Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=61018273814f5d75032ff58620692ba8ae9fb723e07ac93bbaeb52e6cd1a6c27"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "all"
cli-version = "dev"
patches-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "module"
patcher-args = "-e 'Custom branding' -OappIcon=original"
